// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Utils.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class CommandLineUsage : TemplateBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("\r\n\r\n");
 if(!string.IsNullOrWhiteSpace(Description))
{ 
            this.Write("    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Description));
            this.Write("\r\n\r\n");
 } 
 foreach(var argData in Required)
{ 
            this.Write("  ");
            this.Write(this.ToStringHelper.ToStringWithCulture(argData.ToString()));
            this.Write("\r\n");
 } 
            this.Write("\r\n");
 foreach(var argData in Optional)
{ 
            this.Write("  ");
            this.Write(this.ToStringHelper.ToStringWithCulture(argData.ToString()));
            this.Write(" (Optional)\r\n");
 } 
            return this.GenerationEnvironment.ToString();
        }
    }
}
